#!/usr/bin/env python

import os
import shutil
import sys
from transformers import AutoTokenizer, AutoModelForCausalLM

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_CACHE, MODEL_ID

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

#get token from script argument
token = sys.argv[1]

saftey_checker = AutoTokenizer.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
    use_auth_token=token
)

pipe = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    cache_dir=MODEL_CACHE,
    use_auth_token=token
)
